### ISSUE TITLE
Support Compound configuration

### ISSUE THREAD

**Issue by sveine** [turbanoff/RunConfigurationAsAction#13]
Very nice plugin!

In IntelliJ IDEA 2023.1.1 I tried to use a Compound configuration. I have many run configuration in one project, and by having e.g. Action1 as an alias to the run configuration I am working with would be nice. Is it possible to implement?

![image](https://github.com/turbanoff/RunConfigurationAsAction/assets/367125/ff97717c-a0ba-471a-9d14-36194241eaf5)

![image](https://github.com/turbanoff/RunConfigurationAsAction/assets/367125/ced23428-f7a3-4aa0-b2c3-6088d83a9906)

**Comment by turbanoff** [comment]
@sveine can you please check version 1.5 - https://github.com/turbanoff/RunConfigurationAsAction/releases/download/1.5/RunConfigurationAsAction-1.5.jar if it work ok?

**Comment by sveine** [comment]
> @sveine can you please check version 1.5 - https://github.com/turbanoff/RunConfigurationAsAction/releases/download/1.5/RunConfigurationAsAction-1.5.jar if it work ok?

Yes, it is working :-) Created Action1 (ctrl+shift+alt+1) and  Action2 (ctrl+shift+alt+2). Already started to use it. Thank you!
