### ISSUE TITLE
Version 2.1 has broken any Run Configuration as Action functionality

### ISSUE THREAD

**Issue by josh-burton** [turbanoff/RunConfigurationAsAction#15]
My existing actions cannot be found/no longer work, and I cannot add or see any actions to add.

**Comment by turbanoff** [comment]
You can use - https://github.com/turbanoff/RunConfigurationAsAction/releases/download/2.2/RunConfigurationAsAction-2.2.jar
It will appear in JetBrains marketplace soon.

**Comment by turbanoff** [comment]
I've deleted an incorrect version 2.1 from marketplace. You can also use 1.51 - https://plugins.jetbrains.com/plugin/9448-run-configuration-as-action/versions

**Comment by josh-burton** [comment]
Thank you! I thought something like that must have happened.

Thanks for the quick response.
