### ISSUE TITLE
Configurations cannot be run in CLion

### ISSUE THREAD

**Issue by canab** [turbanoff/RunConfigurationAsAction#2]
In the CLion along with the current "Run Configuration" there is also some kind of state called CMake context (Debug, Release, etc.) Users select it as checkbox in the "Run Configurations" popup. This checkbox is visible when current run configuration is of type C/C++ application and is invisible if any other configuration is selected.

The issue is that if the current configuration is of type CMake and (so CMake context is chosen) - it is impossible to run a regular (non-CMake) configuration as action of this plugin. IDE logs an error `Cannot run 'CONF_NAME' on 'Debug'`. 'Debug' is a name of chosen CMake context.

And vice versa: if a regular (non-CMake) configuration is selected (so CMake context is reset and hidden), it is only possible to run any regular configurations, but not CMake one. Error in this case is `Cannot run 'CONF_NAME on '<default>'`

So to make this cool and helpful plugin to work properly on CLion, it have somehow RESET CMake context before run any regular configuration and SET CMake context (to previously selected or first) when user wants to run CMake configuration.

**Comment by turbanoff** [comment]
I've added support of execution targets to plugin. For CLion it means that CMake profiles are supported now.
To download updated version and read release notes - see https://github.com/turbanoff/RunConfigurationAsAction/releases/tag/1.3

**Comment by turbanoff** [comment]
Not fully working(

**Comment by turbanoff** [comment]
Was able to fix. Please try new version.

**Comment by turbanoff** [comment]
@amakeev I've found solution. Thank you for response.
