### ISSUE TITLE
I want to know what is run in cmd Main?

### ISSUE THREAD

**Issue by 625781186** [turbanoff/RunConfigurationAsAction#3]
Run in cmd Main  is it an external tool?
I need this function , can you tell me how to configure it?  thank you!
![image](https://user-images.githubusercontent.com/30521429/53773779-bd5ff380-3f26-11e9-94b4-3511cccd234d.png)

**Comment by turbanoff** [comment]
@625781186 It's my another plugin RunInCmd.
https://plugins.jetbrains.com/plugin/7976-runincmd
It allows to run some Run configurations in cmd window.
