### ISSUE TITLE
Action that builds a specific configuration

### ISSUE THREAD

**Issue by ajdavis** [turbanoff/RunConfigurationAsAction#4]
Hello! I installed this plugin and I now have new actions to Run, Debug, or Profile each of my configurations. However, there is no action to Build a configuration. Can we include a Build action please?

**Comment by turbanoff** [comment]
Hello.
Not sure that I understand the problem. There is existing action 'Build Project' which you can assign shortcut to.
If you have not yet compiled classes in your module which related to your run configuration, IntelliJ will compile them when you try to Run/Debug it.
Can you please describe more details about use case you are interested in?
