### ISSUE TITLE
Custom toolbar action needs 'Edit icon' again and again to display it's icon properly

### ISSUE THREAD

**Issue by gtoth68** [turbanoff/RunConfigurationAsAction#5]
I use a plugin: Run configuration as Action
I created a custom action wich is displayed on the main toolbar after the folder 'Toolbar run action'.
The custom action's goal to run one of my project gradle task. When I added the action I selected an icon file.
After the creation Idea displays the icon correctly but when I restart it it does not displays the given icon but some kind of placeholder. My attachment shows this case.
If I refresh the icon by using 'Customize Menus and Toolbars...' and 'Edit icon' Idea displays the toolbar action correctly again until the next restart.

There has been such Idea version where restart did not imply the need for the procedure written above. Unfortunately I did not remember which was it.

[I reported this issue to JetBrains.](https://youtrack.jetbrains.com/issue/IDEA-233694) They think that the problem is with the plugin. 

IU-193.6494.35, JRE 11.0.5+10-b520.38x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080

Thank you in advance,
Gábor Tóth

**Comment by turbanoff** [comment]
Thank you for reporting!
I'm aware of this issue and it bothers me too. I've tried multiple approached to fix it reliable, but didn't find the solution.
I've asked Jetbrains for help with this issue in their Slack channel. Now I will wait for response.

**Comment by lrayman** [comment]
➕ 1️⃣ 
I have exactly the same issue

**Comment by jr-ramses** [comment]
i, too
I like the plugin, and it would be find when this would working

**Comment by turbanoff** [comment]
I managed to fix it. Update will be available in JetBrains repository next week.
You can try new version here - https://github.com/turbanoff/RunConfigurationAsAction/releases/download/1.4/RunConfigurationAsAction.jar

**Comment by gtoth68** [comment]
I tried your solution. It seems to be working fine. Thank you!
