### ISSUE TITLE
Run configurations with underscores character "_" in their names are not shown properly in a "Find Action" list.

### ISSUE THREAD

**Issue by canab** [turbanoff/RunConfigurationAsAction#6]
All highlighted names on screenshot contain underscores. Some of them are shown properly but some are not. Probably this is an IDE issue or it requires some kind of escaping.
<img width="666" alt="Screenshot 2020-04-05 at 13 55 27" src="https://user-images.githubusercontent.com/275162/78473398-119c5f00-7749-11ea-815f-7af7e441d114.png">

**Comment by canab** [comment]
It seems that only first underscore in each item is missing, the rest are present.

**Comment by turbanoff** [comment]
You are right. Underscore is used as mnemonic in Swing. I will add escaping in the next release.
