### ISSUE TITLE
cannot find runner

### ISSUE THREAD

**Issue by crazyx13th** [turbanoff/RunConfigurationAsAction#7]
Hey there, plugin not working for me with webstorm and npm run commands
thanks!

![grafik](https://user-images.githubusercontent.com/8912561/108961283-6570a900-7677-11eb-9cc2-90a11a6714f2.png)

![grafik](https://user-images.githubusercontent.com/8912561/108961135-322e1a00-7677-11eb-9601-0d54209c8a40.png)
![grafik](https://user-images.githubusercontent.com/8912561/108961784-1c6d2480-7678-11eb-9148-3b0133fbf1d0.png)
![grafik](https://user-images.githubusercontent.com/8912561/108961883-445c8800-7678-11eb-910c-8b3b2ce45272.png)
![grafik](https://user-images.githubusercontent.com/8912561/108961926-50484a00-7678-11eb-9e63-285bb4a03685.png)

**Comment by turbanoff** [comment]
WebStorm has many _executors_ run Run Configuration. Examples: `Run` (just run command), `Debug` (Attach debugger), `Cover` (Run with coverage enabled), etc.
Not all executors can run each Run Configuration, but my plugin registers them all.
You just selected first executor that comes across. Unfortunately `npm` run configurations don't work with `Cover` executor.
You need to use another _executor_. Use search in `Choose Actions To Add` dialog: there should be few actions which execute `start:development`

**Comment by crazyx13th** [comment]
you right! maybe the message should be 
`don't find a run configuration from type 'Cover'`
thanks for you time!!
